### ISSUE TITLE
구글 검색 노출 시키려면 어떻게 해야하나요?

### ISSUE THREAD

**Issue by dgd03146** [hyesungoh/comet-land#109]
## 구글 검색 노출
안녕하세요 만들어주신 블로그 정말 잘 사용하고 있습니다. 너무 이쁘네요! 구글에서 검색하였을때 검색 결과가 노출이 안되는것 같은데 혹시 다른 설정을 해주어야하나요? 제가 깃블로그에 대한 이해가 부족해서요ㅠ

**Comment by hyesungoh** [comment]
안녕하세요! 잘 사용하고 계시다니, 기분이 좋습니다.

[google search console](https://search.google.com/search-console/about)에 등록해주신 다음에, `[블로그 url]/sitemap.xml`을 사이트맵에 제출해주시면 됩니다.

그럼 크롤링 후 지표 확인하실 수 있으십니다. (보톰 며칠 ~ 몇주 정도 걸립니다.)

---

google search console에 직접 등록하실 수도 있지만, 

`comet-land` 설정에 GA ID를 기입하셔서 GA를 통해 등록하시면 더욱 쉽게 등록하실 수 있습니다.

---

사용하시는 블로그 혹은 이력서를 사용 예로 [`comet-land readme`](https://github.com/hyesungoh/comet-land#use-case)에 올리고 싶으시다면 PR 부탁드리겠습니다.

좋은 하루되세요 감사합니다 :D
