### ISSUE TITLE
vercel build실패 문의드려요.

### ISSUE THREAD

**Issue by cptbong** [hyesungoh/comet-land#72]
fork 후 확인차 blogRepo, blogUrl의 값만 변경 후 vercel에 등록하였는데,

Error: The file "/vercel/path0/.next/routes-manifest.json" couldn't be found. This is normally caused by a misconfiguration in your project.

라는 에러가 발생하는데요.
따로 더 해줘야 하는게 있을까요?

**Comment by hyesungoh** [comment]
혹시 등록하실 때 아래 사진처럼 root 설정 해주셨을까요?

![root-dir](https://user-images.githubusercontent.com/26461307/176459016-680a5f61-31d4-4b42-b819-181b8bad3959.png)
